### ISSUE TITLE
Negative value in SpliceAI scores

### ISSUE THREAD

**Issue by aardes** [kircherlab/CADD-scripts#40] opened 2023-03-29 07:37 UTC
Dear, 

I noticed that there are minus signs for some of the SpliceAI scores, specifically in the hg19 data.  

I assume this could be a bug, please take a look.
 
![image](https://user-images.githubusercontent.com/12953535/228457260-d9954b87-a9ad-43fc-8f2d-8a10d1b249a0.png)

regards
Amin

**Comment by aerval** [comment] 2023-03-31 12:41
Dear Amin,

Thank you for raising this issue.
I have checked the examples you have given and tracked it down to the precomputed SpliceAI files that the original authors of SpliceAI have provided. I have not checked the SpliceAI script itself but the [spliceailookup from the Broad](https://spliceailookup.broadinstitute.org/#variant=chr11-1776198-G-GT&hg=37&distance=50&mask=0&precomputed=0) which returns affected scores as '0'. I am not sure what is the cause but would expect it to be floating point number issue.

We won't fix this at this time as it is more of a 'cosmetic' issue that has no consequence for the score but would make it necessary to update a 33GB annotation file. However, we will be sure to fix this in a future CADD release.

Thank you for your help,
Philipp

**Closed by aerval** 2023-03-31 12:41 UTC
